### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Ditti4** [Ezzpify/SteamBulkActivator#1]
Full error message:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '23' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at SteamBulkActivator.Result.responseTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SteamBulkActivator
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1
    CodeBase: file:///E:/Downloads/SteamBulkActivator/SteamBulkActivator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Steam4NET
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Downloads/SteamBulkActivator/Steam4NET.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Things I did prior to this exception occurring:

1. Enter 23 valid keys, no invalid ones.
1. Register all of them. One product was reported as already owned, so I left the results window open, searched for the key (third to last), clicked into the window, copied it and tried to activate it on Steam.
1. Exception occurred. When clicking "Continue", the exception is thrown again and again, making you have to quit the application.

If you need any more details on this, please let me know.

**Comment by Ezzpify** [comment]
Hello @Ditti4 and thanks for the very informative bug report!

1) When you attempted to register the key again, did you leave the other Result window open and clicked REGISTER KEYS, or did you close the other Result window first? 

2) Did you only attempt to register one key the second time, or multiple keys?

I can't seem to replicate the problem, but I have made some changes since the version you are probably using.

**Comment by Ditti4** [comment]
> When you attempted to register the key again, did you leave the other Result window open and clicked REGISTER KEYS, or did you close the other Result window first?

Sorry, I wasn't clear enough on that. The second time, I tried to activate it manually through the Steam Client, not through the bulk activator, just to see what the Steam Client has to say about that exactly.

When trying to replicate the issue again, I unfortunately couldn't do it either. However, if I happen to do it again, I'll definitely let you know (with hopefully more detailed steps to reproduce it)!

**Comment by Ezzpify** [comment]
@Ditti4 right, okay. So the exception occurred by itself without any user input while it was left open in the background?

**Comment by Ditti4** [comment]
Alright, I got it!

What's happening is that when I manually register a key, I think the Bulk Activator still gets the result message from the Steam Client and tries to add it to the result window.

What I did just now (tried it multiple times to confirm it):

1. "Register" 3 keys (already registered)
1. Leave the result window open
1. Register the key through Steam
1. Exception occurred

Your application probably tries to add that result to the result window and tries to find the associated key in the main window which isn't there since it was registered through the Steam Client.

I hope that helps now!

**Comment by Ezzpify** [comment]
Good hunting!
The program is indeed receiving callbacks even when you interact with the client manually.

Changing the [following function](https://github.com/Ezzpify/SteamBulkActivator/blob/master/SteamBulkActivator/Result.cs#L49) to the following should fix this issue!

```
public void AddResult(string result)
{
    //This now means that we will ignore any results if we have more results than keys
    //If we start off with 10 keys, it does NOT make sense to get 11 respones!
    if (_cdKeyList.Count() < _cdKeyResponses.Count() + 1)
        return;

    _cdKeyResponses.Add(new KeyResponse()
    {
        response = result,
        added = false
    });
}
```
