### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seguis** [Ezzpify/SteamBulkActivator#14]
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en SteamBulkActivator.MainForm.connectToSteam()
   en SteamBulkActivator.MainForm.MainForm_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by 123khaled123** [comment]
same

**Comment by seguis** [comment]
I was analyzing, is due to the Steam update, on December 13, I went back to an earlier version of Steam and it worked

**Comment by 123khaled123** [comment]
But i believe you cant get an old version of Steam. Which leaves us to only look forward an update to SteamBulkActivator

**Comment by seguis** [comment]
I luckily I have a previous version copied in another folder, before having made the update

**Comment by darklicius** [comment]
@seguis you can send your steam?

**Comment by 123khaled123** [comment]
For now im using steam website redeem code, its pretty okayish aside from the annoying mail for every code you are activating. But still you can active more than one code at the time. 
https://store.steampowered.com/account/registerkey

**Comment by darklicius** [comment]
R.I.P Steam bulk activactor :(

**Comment by Ezzpify** [comment]
Fixed
