### ISSUE TITLE
humble bundle keys

### ISSUE THREAD

**Issue by M0UL** [Ezzpify/SteamBulkActivator#3]
when generating a key on the humblebundel site. the default selection has space at the start and at the end of the key.  the bulk importer does not recognize this as a key.  it is really annoying to remove those spaces for every key. 
can you make it that it wil remove those spaces automatically?

**Comment by ignaciobfp** [comment]
I think it should be fixed with https://github.com/Ezzpify/SteamBulkActivator/pull/4 , since I had the same problem :)

**Comment by Ezzpify** [comment]
Hello!

Thanks for the feedback. I have merged with pr #4 from @ignaciobfp that fixes this problem, as well as changing the file output.

Thanks.

**Comment by M0UL** [comment]
thank for the update
