### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ChaosTherum** [Ezzpify/SteamBulkActivator#5]
I was curious if it would be possible to add the option for a delay. Like for example 2 minutes between keys so that you can throw a ton of keys at it and just wait for it to complete without hitting the limit and locking your account out.

**Comment by Ezzpify** [comment]
Hello, absolutely that can be done. I will add it to the next version.

**Comment by welcometopwn** [comment]
Looking forward for this update. Really frustrating that Steam has this limit of applying too many keys in a short period.

**Comment by Ezzpify** [comment]
Implemented
