### ISSUE TITLE
[Issue] Examples keys are recognized as valid

### ISSUE THREAD

**Issue by djreisch** [Ezzpify/SteamBulkActivator#6]
Main menu does not ignore the example (greyed) default keys

**Comment by djreisch** [comment]
If I have the time to update this I will, otherwise the keys filled in by that starting layer just need to be ignored. They can be ignored until the program recognizes the first user click, At the point the title could have been "Paste Keys Below" instead of "Valid Key: 4" and once the users clicks the text field the title change change to the number of valid keys.

**Comment by Ezzpify** [comment]
Fixed.
