### ISSUE TITLE
[Issue] Icon cannot be seen on darker themed taskbars

### ISSUE THREAD

**Issue by djreisch** [Ezzpify/SteamBulkActivator#7]
A suggestion. For the longest time I had my own branch of this project working on it by my lonesome. The icon used as of right now cannot bee see on a darker taskbar. Can I suggest using the icon I used (from an old hot-key script based key activator).

The image of my taskbar showing the two different icons (my scanner, current SBA icon, icon I used for SBA)
![capture](https://user-images.githubusercontent.com/1836680/30664528-e2ee0b44-9e02-11e7-8cad-288f6ada12f2.PNG)

**Comment by Ezzpify** [comment]
Fixed. Thanks for the icon.

**Comment by djreisch** [comment]
Did you change the exe icon because it still seems the same. Shows up invisible on my taskbar.

**Comment by Ezzpify** [comment]
Probably icon is cached, pretty sure I changed it. Will look when I'm on pc later.

**Comment by djreisch** [comment]
Yeah I cleared my cache and still there. Double check you changes in both the mainform and the compile configs.
